    let chat_message = [
        "HELLO I’M MAGNETIO I REALLY WHAT TO BE THE MOST POWERFULL MAGNET IN THE UNIVERSE CAN YOU HELP ME?",
        "REALLY? I'M SO EXCITED. I WILL HELP YOU :D LET'S START FROM BUING A NEWSPAPER TO CHARGE ME UP!",
        "WHY? I THOUGHT THAT IT WILL BE FUN.. EHH.... OKAY SO.. I WILL TELL EVERYBODY ON CACTUS THAT YOU ARE BAD PERSON :/ FEELS DEMAGNETIC",
        "WHAT ELECTRONS CAN PAPER ARCHIWE WHEN IT IS SCRATCHING THE GLASS BOTTLE? PLUS OR MINUS? YOU CAN WON 10X MORE ENEGRY :3",
        "YOU CAN BUY A SOCK, WOOL SOCK WITH A LOT OD ELECTRONS",
        "OOOO HELLO EMO GUY, YOU WILL HELP ME WITH YOUR AMAZING HAIR FROM METALIC MUSIC",
        "I'M GLAD TO MEET A DEAD ZEBER",
        "LET'S WORK WITH A HAND HUHHU IT'S LIKE MASTURBATION BUT YOU WILL HELP ME NOT YOU ;*",
        "SOO MUCH ELECTROMAGNENCY, I FEEL INSIDE SHINE, BATTERY AAA + GREAT SOURCE OF ENERGY",
        "YOU THINK THAT THIS IS A GOOD IDEA TO CHARGE ME WITH ATOM ENERGY? OKAY LET'S GO. I FEEL LIKE I'M IN HEAVEN ",
        "CACTU GENERATOR, YOU ARE SERIOUS, WAIT..... OOO..... WHAT????.... THIS IS SOOOOO POWERFULLLLLLLLLL",
        "I WILL BE LIKE A CACTU GOD, CACTU GOD IS THE MOST POWERFUL THING WHAT CAN YOU IMAGINE AND USE"
    ];